#steps:
#  - name: hello
#    image: alpine
#    commands:
#      - echo "CI works!"
#      - uname -a
#      - date

steps:
  - name: hello
    commands:
      - echo "CI works!!"
      - uname -a


